# Generated by Django 3.2 on 2024-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='decription',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
